spring:
  application:
    name: lab-7-8
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Misha20010712
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: UTF-8
